name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK (adjust version as needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build Spring Boot app (Maven example)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # --- OR if you use Gradle instead ---
      # - name: Build with Gradle
      #   run: ./gradlew build -x test

      # 4. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=app/target/app-1.0.0.jar -t my-app:latest .

      # 6. Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/spring-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME